<?php require __DIR__.'/../inc/bootstrap.php';need('admin');
function wipe($x){$i=$x['id'];if($x['role']=='lecturer')q('UPDATE courses SET lecturer_id=NULL WHERE lecturer_id=?',[$i]);
else{foreach(['enrollments','attendance','marks','submissions'] as $t)q("DELETE FROM $t WHERE student_id=?",[$i]);
foreach(q('SELECT * FROM applications WHERE username=?',[$x['username']])->fetchAll() as $a)foreach(['cert','photo','slip'] as $f)if($a[$f])ctype_digit((string)$a[$f])&&q('DELETE FROM files WHERE id=?',[(int)$a[$f]]);
q('DELETE FROM applications WHERE username=?',[$x['username']]);}
q('DELETE FROM users WHERE id=?',[$i]);}
$nav=['pending'=>'Pending Applications','students'=>'Students','lecturers'=>'Lecturers','accounting'=>'Accounting &amp; Hall Tickets','courses'=>'Courses','enroll'=>'Enrollment','attendance'=>'Attendance','news'=>'Announcements','backup'=>'Backup &amp; Restore','security'=>'Security','logs'=>'View Logs'];$p=$_GET['p']??'pending';
if($p=='backup'&&isset($_GET['dl'])){header('Content-Type: application/sql');header('Content-Disposition: attachment; filename=muit-backup-'.date('Ymd').'.sql');foreach(['users','courses','applications','enrollments','attendance','marks','assignments','submissions','announcements'] as $t){echo "DELETE FROM $t;\n";foreach(q("SELECT * FROM $t")->fetchAll() as $r)echo "INSERT INTO $t(".implode(',',array_keys($r)).") VALUES(".implode(',',array_map(fn($v)=>$v===null?'NULL':db()->quote($v),$r)).");\n";}exit;}
if($_SERVER['REQUEST_METHOD']=='POST'){$d=$_POST['do']??'';$id=(int)($_POST['id']??0);if($d)logit('admin_'.$d,'target #'.$id);
if($d=='approve'){$a=q('SELECT * FROM applications WHERE id=? AND status="pending"',[$id])->fetch();if($a){$n=str_pad($id,4,'0',STR_PAD_LEFT);$reg='MUIT/'.date('Y')."/$n";$us='muit'.date('y').$n;$pw=substr(bin2hex(random_bytes(5)),0,8);
q('INSERT INTO users(username,password,role,name,email,phone,reg_no,course_id) VALUES(?,?,?,?,?,?,?,?)',[$us,password_hash($pw,PASSWORD_DEFAULT),'student',$a['full_name'],$a['email'],$a['phone'],$reg,$a['course_id']]);
q('INSERT INTO enrollments VALUES(?,?)',[db()->lastInsertId(),$a['course_id']]);q('UPDATE applications SET status="approved",temp_pass=?,username=? WHERE id=?',[$pw,$us,$id]);
@mail($a['email'],'MUIT application approved',"Username: $us\nPassword: $pw\nLogin: ".env('APP_URL','').'/login.php');
flash('Approved. Username <b>'.e($us).'</b>, password <b>'.e($pw).'</b>. The applicant can also collect these on the status page.');}}
if($d=='reject')q('UPDATE applications SET status="rejected" WHERE id=?',[$id]);
if($d=='deluser'){$x=q('SELECT * FROM users WHERE id=? AND role<>"admin"',[$id])->fetch();if($x){wipe($x);flash('Account and all related data deleted.');}}
if($d=='delapp'){$a=q('SELECT * FROM applications WHERE id=?',[$id])->fetch();if($a){$x=q('SELECT * FROM users WHERE username=? AND role="student"',[$a['username']??''])->fetch();if($x)wipe($x);foreach(['cert','photo','slip'] as $f)if($a[$f])ctype_digit((string)$a[$f])&&q('DELETE FROM files WHERE id=?',[(int)$a[$f]]);q('DELETE FROM applications WHERE id=?',[$id]);flash('Application and all related data deleted.');}}
if($d=='toggle'&&in_array($_POST['f'],['paid','hall_ok']))q('UPDATE users SET '.$_POST['f'].'=1-'.$_POST['f'].' WHERE id=?',[$id]);
if($d=='addlec'){try{q('INSERT INTO users(username,password,role,name,email) VALUES(?,?,?,?,?)',[trim($_POST['username']),password_hash($_POST['password'],PASSWORD_DEFAULT),'lecturer',$_POST['name'],$_POST['email']]);flash('Lecturer added.');}catch(Exception $x){flash('That username already exists.');}}
if($d=='addcourse')q('INSERT INTO courses(code,name,lecturer_id) VALUES(?,?,?)',[$_POST['code'],$_POST['name'],$_POST['lid']?:null]);
if($d=='delcourse')q('DELETE FROM courses WHERE id=?',[$id]);
if($d=='assign'){q('UPDATE courses SET lecturer_id=? WHERE id=?',[$_POST['lid']?:null,$id]);flash('Lecturer assignment saved.');}
if($d=='enroll'){q('INSERT IGNORE INTO enrollments VALUES(?,?)',[(int)$_POST['sid'],(int)$_POST['cid']]);flash('Student enrolled.');}
if($d=='unenroll')q('DELETE FROM enrollments WHERE student_id=? AND course_id=?',[(int)$_POST['sid'],(int)$_POST['cid']]);
if($d=='addnews')q('INSERT INTO announcements(title,body) VALUES(?,?)',[$_POST['title'],$_POST['body']]);
if($d=='delnews')q('DELETE FROM announcements WHERE id=?',[$id]);
if($d=='restore'&&!empty($_FILES['sql']['tmp_name'])){$n=0;foreach(explode("\n",file_get_contents($_FILES['sql']['tmp_name'])) as $l)if(preg_match('/^(DELETE FROM|INSERT INTO) /',$l)){db()->exec($l);$n++;}flash("Restore complete ($n statements).");}
if($d=='account'){$me=me();$nu=trim($_POST['username']);$np=$_POST['new_password'];
if(!password_verify($_POST['current'],$me['password']))flash('Current password is wrong.');
elseif(!preg_match('/^[A-Za-z0-9_.]{4,30}$/',$nu))flash('Username must be 4-30 characters: letters, numbers, dot or underscore.');
elseif(q('SELECT 1 FROM users WHERE username=? AND id<>?',[$nu,$me['id']])->fetch())flash('That username is already taken.');
elseif($np!==''&&(strlen($np)<8||$np!==$_POST['confirm']))flash('New password must be at least 8 characters and match the confirmation.');
else{q('UPDATE users SET username=? WHERE id=?',[$nu,$me['id']]);if($np!=='')q('UPDATE users SET password=? WHERE id=?',[password_hash($np,PASSWORD_DEFAULT),$me['id']]);$_SESSION['u']['username']=$nu;flash('Admin account updated. Use the new details next time you log in.');}}
go('?p='.$p);}
head(strip_tags(html_entity_decode($nav[$p]??'Admin')),$nav);
if($p=='pending'){$r=[];$f=fn($x)=>$x?'<a href="/file.php?id='.e($x).'" target=_blank>View</a>':'-';
foreach(q('SELECT a.*,c.code FROM applications a LEFT JOIN courses c ON c.id=a.course_id ORDER BY a.status="pending" DESC,a.id DESC')->fetchAll() as $a)$r[]=['#'.$a['id'],e($a['full_name']).'<br><small class=muted>'.e($a['email']).' / '.e($a['phone']).'</small>',e($a['code']),e($a['dob']).' / '.e($a['gender']),$f($a['cert']).' | '.$f($a['photo']).' | '.$f($a['slip']),'<span class="tag '.$a['status'].'">'.$a['status'].'</span>',($a['status']=='pending'?pf('approve',$a['id'],'Approve','ok').pf('reject',$a['id'],'Reject','no'):'').pf('delapp',$a['id'],'Delete','no')];
tbl(['Ref','Applicant','Course','DOB / Gender','Documents','Status','Action'],$r);}
elseif($p=='students'){$r=[];foreach(q('SELECT u.*,c.name cn FROM users u LEFT JOIN courses c ON c.id=u.course_id WHERE role="student"')->fetchAll() as $s)$r[]=[e($s['reg_no']),e($s['name']),e($s['cn']),e($s['username']),pf('deluser',$s['id'],'Delete','no')];tbl(['Reg No','Name','Course','Username',''],$r);}
elseif($p=='lecturers'){echo '<form method=post class="card form"><input type=hidden name=do value=addlec><label>Full name<input name=name required></label><label>Email<input type=email name=email></label><label>Username<input name=username required></label><label>Password<input name=password minlength=6 required></label><div class=full><button class="btn ok">Add lecturer</button></div></form>';
$r=[];foreach(q('SELECT u.*,(SELECT GROUP_CONCAT(code SEPARATOR ", ") FROM courses WHERE lecturer_id=u.id) cs FROM users u WHERE role="lecturer"')->fetchAll() as $s)$r[]=[e($s['name']),e($s['username']),e($s['email']),e($s['cs']?:'None assigned'),pf('deluser',$s['id'],'Delete','no')];tbl(['Name','Username','Email','Assigned courses',''],$r);}
elseif($p=='accounting'){$r=[];foreach(q('SELECT * FROM users WHERE role="student"')->fetchAll() as $s)$r[]=[e($s['reg_no']),e($s['name']),'<span class="tag '.($s['paid']?'approved':'pending').'">'.($s['paid']?'Paid':'Not paid').'</span>',pf('toggle',$s['id'],$s['paid']?'Mark not paid':'Mark paid',$s['paid']?'warn':'ok','<input type=hidden name=f value=paid>'),'<span class="tag '.($s['hall_ok']?'approved':'pending').'">'.($s['hall_ok']?'Allowed':'Blocked').'</span>',pf('toggle',$s['id'],$s['hall_ok']?'Block hall ticket':'Allow hall ticket',$s['hall_ok']?'warn':'','<input type=hidden name=f value=hall_ok>')];tbl(['Reg No','Name','Payment','','Hall ticket',''],$r);}
elseif($p=='courses'){echo '<form method=post class="card row"><input type=hidden name=do value=addcourse><input name=code placeholder=Code required><input name=name placeholder="Course name" required><select name=lid><option value="">No lecturer</option>'.opts('SELECT id,name FROM users WHERE role="lecturer"').'</select><button class="btn ok">Add course</button></form>';
$r=[];foreach(q('SELECT c.*,u.name ln FROM courses c LEFT JOIN users u ON u.id=c.lecturer_id')->fetchAll() as $c)$r[]=[e($c['code']),e($c['name']),'<form method=post class=inl><input type=hidden name=id value='.$c['id'].'><select name=lid style="width:auto;display:inline-block;margin:0"><option value="">No lecturer</option>'.opts('SELECT id,name FROM users WHERE role="lecturer"',[],$c['lecturer_id']).'</select> <button class="btn sm ok" name=do value=assign>Assign</button></form>',pf('delcourse',$c['id'],'Delete','no')];tbl(['Code','Course','Lecturer',''],$r);}
elseif($p=='enroll'){echo '<form method=post class="card row"><input type=hidden name=do value=enroll><select name=sid>'.opts('SELECT id,CONCAT(reg_no," ",name) FROM users WHERE role="student"').'</select><select name=cid>'.opts('SELECT id,name FROM courses').'</select><button class="btn ok">Enroll student</button></form>';
$r=[];foreach(q('SELECT u.id sid,u.name,c.id cid,c.name cn FROM enrollments e JOIN users u ON u.id=e.student_id JOIN courses c ON c.id=e.course_id')->fetchAll() as $x)$r[]=[e($x['name']),e($x['cn']),pf('unenroll',0,'Remove','no','<input type=hidden name=sid value='.$x['sid'].'><input type=hidden name=cid value='.$x['cid'].'>')];tbl(['Student','Course',''],$r);}
elseif($p=='attendance'){$r=[];foreach(q('SELECT c.code,c.name,COUNT(a.id) t,COALESCE(ROUND(100*AVG(a.present)),0) pct FROM courses c LEFT JOIN attendance a ON a.course_id=c.id GROUP BY c.id')->fetchAll() as $x)$r[]=[e($x['code']),e($x['name']),$x['t'],$x['pct'].'%'];tbl(['Code','Course','Records','Average attendance'],$r);}
elseif($p=='news'){echo '<form method=post class="card form"><input type=hidden name=do value=addnews><label class=full>Title<input name=title required></label><label class=full>Message<textarea name=body rows=3 required></textarea></label><div class=full><button class="btn ok">Post announcement</button></div></form>';
$r=[];foreach(q('SELECT * FROM announcements ORDER BY id DESC')->fetchAll() as $a)$r[]=[e($a['title']),e($a['created']),pf('delnews',$a['id'],'Delete','no')];tbl(['Title','Posted',''],$r);}
elseif($p=='backup')echo '<div class=grid3><div class=card><h3>Export &amp; download</h3><p class=muted>Download a full SQL backup.</p><a class=btn href="?p=backup&dl=1">Download backup</a></div><form method=post enctype=multipart/form-data class=card><h3>Restore</h3><p class=muted>Upload a backup made here. Existing data is replaced.</p><input type=hidden name=do value=restore><input type=file name=sql accept=.sql required><br><br><button class="btn no" onclick="return confirm(\'Replace all data?\')">Restore backup</button></form></div>';
elseif($p=='security'){$ad=me();echo '<form method=post class="card narrow" style="margin:0"><input type=hidden name=do value=account><label>Admin username<input name=username value="'.e($ad['username']).'" required></label><label>New password <small class=muted>(leave empty to keep current)</small><input type=password name=new_password minlength=8 autocomplete=new-password></label><label>Confirm new password<input type=password name=confirm autocomplete=new-password></label><label>Current password <small class=muted>(required to save)</small><input type=password name=current required></label><button class="btn ok big">Update account</button><p class=muted>Passwords are stored hashed. Uploads accept JPG, PNG and PDF up to 3 MB.</p></form>';}
elseif($p=='logs'){$f=trim($_GET['q']??'');echo '<form class="card row" method=get><input type=hidden name=p value=logs><input name=q value="'.e($f).'" placeholder="Search by user, action or detail"><button class=btn>Search</button></form>';
$r=[];foreach(q('SELECT * FROM logs WHERE username LIKE ? OR action LIKE ? OR detail LIKE ? ORDER BY id DESC LIMIT 300',["%$f%","%$f%","%$f%"])->fetchAll() as $x)$r[]=[e($x['created']),e($x['username']),'<span class="tag '.(strpos($x['action'],'fail')!==false?'rejected':'approved').'">'.e($x['action']).'</span>',e($x['detail']),e($x['ip'])];tbl(['Time','User','Action','Detail','IP'],$r);}
foot();
