<?php require __DIR__.'/../inc/bootstrap.php';need('lecturer');$L=me();
$nav=['profile'=>'My Profile','courses'=>'My Courses','students'=>'My Students','attendance'=>'Record Attendance','marks'=>'Enter Marks','assign'=>'Manage Assignments','perf'=>'Student Performance'];$p=$_GET['p']??'profile';
$own=fn($c)=>q('SELECT 1 FROM courses WHERE id=? AND lecturer_id=?',[(int)$c,$L['id']])->fetch();$my='SELECT id,CONCAT(code," - ",name) FROM courses WHERE lecturer_id=?';
if($_SERVER['REQUEST_METHOD']=='POST'){$d=$_POST['do']??'';$c=(int)($_POST['c']??0);
if($d=='att'&&$own($c)){q('DELETE FROM attendance WHERE course_id=? AND day=?',[$c,$_POST['d']]);foreach(q('SELECT student_id FROM enrollments WHERE course_id=?',[$c])->fetchAll() as $s)q('INSERT INTO attendance(course_id,student_id,day,present) VALUES(?,?,?,?)',[$c,$s['student_id'],$_POST['d'],(($_POST['st'][$s['student_id']]??'0')=='1')?1:0]);flash('Attendance saved.');go("?p=attendance&c=$c&d=".$_POST['d']);}
if($d=='addmark'&&$own($c)){$sc=(float)$_POST['score'];$mx=(float)$_POST['max'];if($mx<=0||$sc<0||$sc>$mx)flash('Score must be between 0 and the maximum.');else{q('INSERT INTO marks(course_id,student_id,assessment,score,max_score) VALUES(?,?,?,?,?)',[$c,(int)$_POST['sid'],$_POST['assessment'],$sc,$mx]);flash('Mark added.');}go("?p=marks&c=$c");}
if($d=='editmark'){$sc=(float)$_POST['score'];$mx=(float)$_POST['max'];if($mx<=0||$sc<0||$sc>$mx)flash('Score must be between 0 and the maximum.');else{q('UPDATE marks m JOIN courses c ON c.id=m.course_id SET m.assessment=?,m.score=?,m.max_score=? WHERE m.id=? AND c.lecturer_id=?',[$_POST['assessment'],$sc,$mx,(int)$_POST['id'],$L['id']]);flash('Mark updated.');}go('?p=marks&c='.$c);}
if($d=='delmark'){q('DELETE m FROM marks m JOIN courses c ON c.id=m.course_id WHERE m.id=? AND c.lecturer_id=?',[(int)$_POST['id'],$L['id']]);flash('Mark deleted.');go('?p=marks&c='.$c);}
if($d=='addas'&&$own($c)){q('INSERT INTO assignments(course_id,title,body,due) VALUES(?,?,?,?)',[$c,$_POST['title'],$_POST['body'],$_POST['due']]);flash('Assignment published.');go('?p=assign');}
if($d=='delas'){q('DELETE a FROM assignments a JOIN courses c ON c.id=a.course_id WHERE a.id=? AND c.lecturer_id=?',[(int)$_POST['id'],$L['id']]);go('?p=assign');}}
head($nav[$p]??'Lecturer',$nav);
if($p=='profile')echo '<div class="card prof"><div class=avatar>'.e(strtoupper($L['name'][0])).'</div><div><h2>'.e($L['name']).'</h2><p class=muted>'.e($L['email']).'</p><span class="tag approved">Lecturer</span></div></div>';
elseif($p=='courses'){$r=[];foreach(q('SELECT c.*,(SELECT COUNT(*) FROM enrollments WHERE course_id=c.id) n FROM courses c WHERE lecturer_id=?',[$L['id']])->fetchAll() as $c)$r[]=[e($c['code']),e($c['name']),$c['n']];tbl(['Code','Course','Students'],$r);}
elseif($p=='students'){$r=[];foreach(q('SELECT u.name,u.reg_no,u.email,c.name cn FROM users u JOIN enrollments e ON e.student_id=u.id JOIN courses c ON c.id=e.course_id WHERE c.lecturer_id=?',[$L['id']])->fetchAll() as $s)$r[]=[e($s['name']),e($s['reg_no']),e($s['cn']),e($s['email'])];tbl(['Name','Reg No','Course','Email'],$r);}
elseif($p=='attendance'){$cid=(int)($_GET['c']??0);$day=$_GET['d']??date('Y-m-d');
echo '<form class="card row" method=get><input type=hidden name=p value=attendance><select name=c>'.opts($my,[$L['id']],$cid).'</select><input type=date name=d value="'.e($day).'"><button class=btn>Load class</button></form>';
if($cid&&$own($cid)){echo '<form method=post><input type=hidden name=do value=att><input type=hidden name=c value='.$cid.'><input type=hidden name=d value="'.e($day).'"><div class="row" style="margin-bottom:12px"><button type=button class="btn sm ok" onclick="document.querySelectorAll(\'input[type=radio][value=&quot;1&quot;]\').forEach(r=>r.checked=true)">Mark all present</button><button type=button class="btn sm no" onclick="document.querySelectorAll(\'input[type=radio][value=&quot;0&quot;]\').forEach(r=>r.checked=true)">Mark all absent</button></div>';
$r=[];foreach(q('SELECT u.id,u.name,u.reg_no FROM users u JOIN enrollments e ON e.student_id=u.id WHERE e.course_id=? ORDER BY u.name',[$cid])->fetchAll() as $s){$pr=q('SELECT present FROM attendance WHERE course_id=? AND student_id=? AND day=?',[$cid,$s['id'],$day])->fetchColumn();$on=($pr===false||$pr);
$r[]=[e($s['name']),e($s['reg_no']),'<label class=pa><input type=radio name="st['.$s['id'].']" value="1"'.($on?' checked':'').'><span class=p>Present</span></label> <label class=pa><input type=radio name="st['.$s['id'].']" value="0"'.($on?'':' checked').'><span class=a>Absent</span></label>'];}
tbl(['Student','Reg No','Attendance'],$r);echo '<button class="btn ok">Save attendance</button></form>';}}
elseif($p=='marks'){$cid=(int)($_GET['c']??0);echo '<form class="card row" method=get><input type=hidden name=p value=marks><select name=c>'.opts($my,[$L['id']],$cid).'</select><button class=btn>Open course</button></form>';
if($cid&&$own($cid)){echo '<form method=post class="card row"><input type=hidden name=do value=addmark><input type=hidden name=c value='.$cid.'><select name=sid>'.opts('SELECT u.id,u.name FROM users u JOIN enrollments e ON e.student_id=u.id WHERE e.course_id=?',[$cid]).'</select><input name=assessment placeholder="Assessment e.g. CAT 1" required><input type=number step=0.1 min=0 name=score placeholder=Score required><input type=number step=0.1 min=0.1 name=max placeholder="Out of (e.g. 50)" required><button class="btn ok">Add mark</button></form>';
$r=[];foreach(q('SELECT m.*,u.name FROM marks m JOIN users u ON u.id=m.student_id WHERE m.course_id=? ORDER BY u.name,m.id',[$cid])->fetchAll() as $m)$r[]=[e($m['name']),'<form method=post class=editrow><input type=hidden name=c value='.$cid.'><input type=hidden name=id value='.$m['id'].'><input name=assessment value="'.e($m['assessment']).'" required><input type=number step=0.1 min=0 name=score value="'.($m['score']+0).'" required><b>/</b><input type=number step=0.1 min=0.1 name=max value="'.($m['max_score']+0).'" required><button class="btn sm" name=do value=editmark>Save</button></form>',round($m['score']/max($m['max_score'],0.1)*100,1).'%',pf('delmark',$m['id'],'Delete','no','<input type=hidden name=c value='.$cid.'>')];tbl(['Student','Assessment / Score / Out of','Percent','Action'],$r);}}
elseif($p=='assign'){echo '<form method=post class="card form"><input type=hidden name=do value=addas><label>Course<select name=c>'.opts($my,[$L['id']]).'</select></label><label>Due date<input type=date name=due required></label><label class=full>Title<input name=title required></label><label class=full>Instructions<textarea name=body rows=3 required></textarea></label><div class=full><button class="btn ok">Publish assignment</button></div></form>';
$r=[];foreach(q('SELECT a.*,c.code,(SELECT COUNT(*) FROM submissions WHERE assignment_id=a.id) n FROM assignments a JOIN courses c ON c.id=a.course_id WHERE c.lecturer_id=? ORDER BY a.id DESC',[$L['id']])->fetchAll() as $a)$r[]=[e($a['code']),e($a['title']),e($a['due']),$a['n'],pf('delas',$a['id'],'Delete','no')];tbl(['Course','Title','Due','Submissions',''],$r);}
elseif($p=='perf'){$r=[];foreach(q('SELECT u.name,c.code,(SELECT ROUND(AVG(score/max_score*100),1) FROM marks WHERE student_id=u.id AND course_id=c.id) av,(SELECT ROUND(100*AVG(present)) FROM attendance WHERE student_id=u.id AND course_id=c.id) at FROM users u JOIN enrollments e ON e.student_id=u.id JOIN courses c ON c.id=e.course_id WHERE c.lecturer_id=?',[$L['id']])->fetchAll() as $s)$r[]=[e($s['name']),e($s['code']),($s['av']===null?'-':$s['av'].'%'),$s['at']===null?'-':$s['at'].'%'];tbl(['Student','Course','Average mark (%)','Attendance'],$r);}
foot();
